module.exports.users = [
  {
    id: 1,
    firstName: "Terry",
    lastName: "Medhurst",
    age: 50,
    gender: "male",
    email: "atuny0@sohu.com",
    phone: "+63 791 675 8914",
    username: "atuny0",
  },
  {
    id: 2,
    firstName: "Alice",
    lastName: "Johnson",
    age: 32,
    gender: "female",
    email: "alice@example.com",
    phone: "+1 555 123 4567",
    username: "alice123",
  },
  {
    id: 3,
    firstName: "John",
    lastName: "Doe",
    age: 28,
    gender: "male",
    email: "john.doe@example.com",
    phone: "+44 20 1234 5678",
    username: "johndoe",
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Smith",
    age: 25,
    gender: "female",
    email: "emily.smith@example.com",
    phone: "+61 3 9876 5432",
    username: "emily.smith",
  },
  {
    id: 5,
    firstName: "Michael",
    lastName: "Williams",
    age: 38,
    gender: "male",
    email: "michaelw@example.com",
    phone: "+1 555 987 6543",
    username: "michael.w",
  },
  {
    id: 6,
    firstName: "Emma",
    lastName: "Brown",
    age: 29,
    gender: "female",
    email: "emma@example.com",
    phone: "+44 20 9876 5432",
    username: "emma.brown",
  },
  {
    id: 7,
    firstName: "Christopher",
    lastName: "Lee",
    age: 42,
    gender: "male",
    email: "chris.lee@example.com",
    phone: "+61 2 9876 5432",
    username: "chris.lee",
  },
  {
    id: 8,
    firstName: "Olivia",
    lastName: "Johnson",
    age: 27,
    gender: "female",
    email: "olivia.j@example.com",
    phone: "+1 555 876 5432",
    username: "olivia.john",
  },
  {
    id: 9,
    firstName: "Daniel",
    lastName: "Martinez",
    age: 33,
    gender: "male",
    email: "daniel.m@example.com",
    phone: "+44 20 8765 4321",
    username: "dan.m",
  },
  {
    id: 10,
    firstName: "Sophia",
    lastName: "Clark",
    age: 35,
    gender: "female",
    email: "sophia.clark@example.com",
    phone: "+1 555 765 4321",
    username: "sophia.clark",
  },
];